### ISSUE TITLE
Internal system time now broken

### ISSUE THREAD

**Issue by agenorsoares** [exdial/anbernic-apps#5]
Is it possible to make timezone selectable? Also, it broke internal system time. It resets to a fixed time everytime the device restarts or reboots. How to revert changes without flashing the stock OS again?

Another strange behavior is, device is locking the screen (turning off) after 1min (same time as set on settings) regardless of being used or not after a fresh boot. Then, the behavior is gone completely.

Edit: lock screen stopped for now, selected "never" in settings, restarted the device, then set "1min" and restarted again.

Edit: fixed the clock by changing this segment of code, which is correct for my tz:
## Configure timezone
echo "Brazil/East" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata
timedatectl set-timezone Brazil/East

**Comment by exdial** [comment]
Hey @agenorsoares, thank you for your question.
Unfortunately, there is no way to make a time zone selection as all changes are made in non-interactive mode.
Regarding the internal system time, this behavior is probably due to power loss issues. You can revert the changes directly by logging into the device via SSH and reconfiguring the timezone to your liking, or you can make a fork change to the code.
No idea about the lock screen issue, `anbernic-apps` doesn't change the lock or screen settings.
